name: Run Python Program

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-program:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run word_count.py automatically
      run: |
        echo "=== Запуск програми ==="
        python Documents/programming-lab6-Shkvarok/word_count.py <<EOF
        Це тестовий текст для автоматичного запуску.
        EOF
